import Head from 'next/head';
import Image from 'next/image';
import ChangeTitle from '../components/ChangeTitle';
import ClientOnly from '../components/ClientOnly';
import LogIn from '../components/LogIn';
import PlaceImages from '../components/PlaceImages';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/router';
import PleaseSignIn from '../components/PleaseSignIn';

export default function Home() {
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>Layout Projekt</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <ClientOnly>
          <PleaseSignIn>
            <PlaceImages
              projectId={router.query.postid}
              permalink={router.query.permalink}
            />
          </PleaseSignIn>
          {/* <ChangeTitle /> */}
        </ClientOnly>
      </main>

      <footer></footer>
    </div>
  );
}
