import Head from 'next/head';
import Image from 'next/image';
import ChangeTitle from '../components/ChangeTitle';
import ClientOnly from '../components/ClientOnly';
import LogIn from '../components/LogIn';
import styles from '../styles/Home.module.css';
import { useRouter } from 'next/router';
import PlaceProjects from '../components/PlaceProjects';

export default function Home() {
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <ClientOnly>
          <PlaceProjects pageId={router.query.pageid} />
        </ClientOnly>
      </main>

      <footer></footer>
    </div>
  );
}
