import Head from 'next/head';
import ClientOnly from '../components/ClientOnly';
import LogIn from '../components/LogIn';

export default function Login() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <ClientOnly>
          <LogIn />
        </ClientOnly>
      </main>

      <footer></footer>
    </div>
  );
}
